/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uqf4ExteYjvaZmM1EKGtky
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantseDc86RmVIv7G } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: eDC86RmVIv7g/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantseDc86RmVIv7G
});
