/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uqf4ExteYjvaZmM1EKGtky
import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uqf4ExteYjvaZmM1EKGtky/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: uqf4ExteYjvaZmM1EKGtky/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
